function handleNestErrors(error) {
  console.log('Something bad happened')
}
